-- Generated from generator/demo_specs/aws-thailand-healthcare-hie.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-healthcare-hie
-- This is the schema that is actually deployed for THAILAND_HEALTHCARE_HIE.

-- Alerts fire on the bottom tail of Consent Coverage
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_CONSENT_COVERAGE) AS T
  FROM RAW.LAB_RESULTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CONSENT_COVERAGE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CONSENT_COVERAGE), 2) AS AVG_CONSENT_COVERAGE,
  ROUND(AVG(f.KPI_RECORD_COMPLETENESS), 2) AS AVG_RECORD_COMPLETENESS,
  ROUND(AVG(f.KPI_AVG_RESPONSE_TIME), 2) AS AVG_RESPONSE_TIME,
  ROUND(AVG(f.KPI_INTEGRATION_ERRORS), 2) AS AVG_INTEGRATION_ERRORS,
  ROUND(AVG(f.KPI_DUPLICATE_RATE), 2) AS AVG_DUPLICATE_RATE
FROM RAW.LAB_RESULTS f
JOIN RAW.THAI_HEALTH_SYSTEM e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CONSENT_COVERAGE), 2) AS AVG_CONSENT_COVERAGE,
  ROUND(AVG(f.KPI_RECORD_COMPLETENESS), 2) AS AVG_RECORD_COMPLETENESS,
  ROUND(AVG(f.KPI_AVG_RESPONSE_TIME), 2) AS AVG_RESPONSE_TIME,
  ROUND(AVG(f.KPI_INTEGRATION_ERRORS), 2) AS AVG_INTEGRATION_ERRORS,
  ROUND(AVG(f.KPI_DUPLICATE_RATE), 2) AS AVG_DUPLICATE_RATE
FROM RAW.LAB_RESULTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CONSENT_COVERAGE) AS KPI_CONSENT_COVERAGE, AVG(KPI_INTEGRATION_ERRORS) AS KPI_INTEGRATION_ERRORS, AVG(KPI_RECORD_COMPLETENESS) AS KPI_RECORD_COMPLETENESS, AVG(KPI_DUPLICATE_RATE) AS KPI_DUPLICATE_RATE, AVG(KPI_AVG_RESPONSE_TIME) AS KPI_AVG_RESPONSE_TIME FROM RAW.LAB_RESULTS),
     en AS (SELECT SUM(KPI_RECORDS_EXCHANGED_MTD) AS KPI_RECORDS_EXCHANGED_MTD, SUM(KPI_CONNECTED_FACILITIES) AS KPI_CONNECTED_FACILITIES FROM RAW.THAI_HEALTH_SYSTEM)
  SELECT 1 AS SORT_ORDER, 'Records Exchanged (MTD)' AS TITLE, KPI_RECORDS_EXCHANGED_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_RECORDS_EXCHANGED_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Consent Coverage' AS TITLE, KPI_CONSENT_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CONSENT_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Integration Errors' AS TITLE, KPI_INTEGRATION_ERRORS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_INTEGRATION_ERRORS), 2) AS DECIMAL(38,2))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Connected Facilities' AS TITLE, KPI_CONNECTED_FACILITIES AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CONNECTED_FACILITIES)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Record Completeness' AS TITLE, KPI_RECORD_COMPLETENESS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RECORD_COMPLETENESS), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Duplicate Rate' AS TITLE, KPI_DUPLICATE_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DUPLICATE_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Avg Response Time' AS TITLE, KPI_AVG_RESPONSE_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_RESPONSE_TIME)) AS DECIMAL(38,0))) || 'ms' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
