-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Clinical Data Exchange
-- ============================================================================
USE DATABASE CLINICAL_HIE;
USE SCHEMA ML;

-- ML.FORECAST: DISEASE_PREVALENCE_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.DISEASE_PREVALENCE_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.POPULATION_HEALTH'),
  SERIES_COLNAME => 'CONDITION_REGION',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.DISEASE_PREVALENCE_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.DISEASE_PREVALENCE_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: OUTCOME_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.OUTCOME_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREATMENT_OUTCOMES'),
  SERIES_COLNAME => 'HOSPITAL_PROCEDURE',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.OUTCOME_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.OUTCOME_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREATMENT_OUTCOMES'), SERIES_COLNAME => 'HOSPITAL_PROCEDURE', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

