-- ============================================================================
-- 99_RESET.SQL — Reset Clinical Data Exchange to clean demo state
-- ============================================================================
USE DATABASE CLINICAL_HIE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_COHORTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_OUTCOMES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_CHECK_CONSENT SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PATIENT_COHORTS REFRESH;
ALTER DYNAMIC TABLE CURATED.TREATMENT_OUTCOMES REFRESH;
ALTER DYNAMIC TABLE CURATED.NETWORK_UTILIZATION REFRESH;
ALTER DYNAMIC TABLE CURATED.POPULATION_HEALTH REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM CLINICAL_HIE.RAW.PATIENT_REGISTRY → 2000000
-- SELECT COUNT(*) FROM CLINICAL_HIE.RAW.CLINICAL_ENCOUNTERS → 8000000
-- SELECT COUNT(*) FROM CLINICAL_HIE.RAW.CONSENT_REGISTRY WHERE STATUS = 'ACTIVE' → >1800000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_CHECK_CONSENT RESUME;
ALTER TASK IF EXISTS APP.TASK_UPDATE_OUTCOMES RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_COHORTS RESUME;
